### ISSUE TITLE
Make 'message' parameter optional

### ISSUE THREAD

**Issue by alihusseinalissa** [vantuan88291/flutter_dropdown_alert#3]
Sometimes we need to show a short message to the user, such as showing "Item deleted successfully" or "No more items", these messages is very short that can be shown in one line, in this case we can pass this message in the 'title' only, there is no need to the 'message' parameter.

I tried passing [null] and [empty string] to the 'message' parameter, but the title then would be shown in the upper part of the alert, if the 'message' parameter been optional, title must be centered vertically in the alert.

**Comment by vantuan88291** [comment]
Hi, thank for your report. This issue was release at 1.0.3 version. I will close this issue. Thank you
