### ISSUE TITLE
Null check operator used on a null value (_tabListener)

### ISSUE THREAD

**Issue by cyb3rsalih** [vantuan88291/flutter_dropdown_alert#6]
In debug mode, when I tap the alert, debug stopping here.

```
VoidCallBackListenerTab getTabListener() {
    return _tabListener!;
 }
  ```
  
 With this exception in debug console
```
 ════════ Exception caught by gesture ════════
Null check operator used on a null value
```

I initialize the  DropdownAlert without any parameter btw. 

Thanks.

**Comment by vantuan88291** [comment]
Did you run the example project? 
I had add this condition:
` if (_controller?.getTabListener() != null) {
      _controller?.getTabListener()(this.payload, this.type!);
    }`

So it can not be happened btw, please give me more information. Thanks

**Comment by cyb3rsalih** [comment]
No, I just add the DropdownAlert to the root MaterialApp, and where I use

**Comment by vantuan88291** [comment]
Thank for your report, this issue was resolve at **1.0.4** version. Please upgrade to use it, i will close this issue. Thanks
